/*
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.expressiondsl.ide


/**
 * Use this class to register ide components.
 */
class ControlDSLIdeModule extends AbstractControlDSLIdeModule {
}
