/*
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.expressiondsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ControlDSLStandaloneSetup extends ControlDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new ControlDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
