/*
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.expressiondsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ControlDSLRuntimeModule extends AbstractControlDSLRuntimeModule {
}
