/*
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.expressiondsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class ControlDSLUiModule extends AbstractControlDSLUiModule {
}
